# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('week', models.IntegerField(max_length=2)),
                ('points_scored', models.DecimalField(decimal_places=2, max_digits=5)),
                ('roster_rank', models.IntegerField(default=0, max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_key', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('league_year', models.IntegerField(default=2016, max_length=4)),
                ('wins', models.IntegerField(default=0, max_length=2)),
                ('manager', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='scoringlog',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='rankings.Teams'),
        ),
    ]
