# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringlog',
            name='roster_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scoringlog',
            name='week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teams',
            name='league_year',
            field=models.IntegerField(default=2016),
        ),
        migrations.AlterField(
            model_name='teams',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
