# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-30 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_auto_20160930_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringlog',
            name='roster_rank',
        ),
        migrations.AddField(
            model_name='teams',
            name='current_roster_rank',
            field=models.IntegerField(default=0),
        ),
    ]
