# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_auto_20160930_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerRankingsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('win_rank', models.IntegerField()),
                ('ovw_rank', models.IntegerField()),
                ('con_rank', models.IntegerField()),
                ('avg_rank', models.IntegerField()),
                ('ros_rank', models.IntegerField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank_teams', to='rankings.Teams')),
            ],
        ),
    ]
