# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_powerrankingsdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerrankingsdata',
            name='avg_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powerrankingsdata',
            name='con_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powerrankingsdata',
            name='ovw_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powerrankingsdata',
            name='ros_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='powerrankingsdata',
            name='win_rank',
            field=models.IntegerField(default=0),
        ),
    ]
