# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_powerrankingsdata_pow_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerrankingsdata',
            name='pow_rank',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
