# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-05 17:52
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0007_auto_20161005_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerrankingsdata',
            name='pow_rank',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
    ]
