# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0008_auto_20161005_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='league_year',
            field=models.IntegerField(default=2017),
        ),
    ]
